##The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
##
##1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
##
##Let us list the factors of the first seven triangle numbers:
##
## 1: 1
## 3: 1,3
## 6: 1,2,3,6
##10: 1,2,5,10
##15: 1,3,5,15
##21: 1,3,7,21
##28: 1,2,4,7,14,28
##We can see that 28 is the first triangle number to have over five divisors.
##
##What is the value of the first triangle number to have over five hundred divisors?

def triNum(num):
    if num == 0: return 0
    elif num == 995: return 495510
    elif num == 1990: return 1981045
    else: return num + triNum(num-1)

def divs(num):
    total = 0
    for x in range(1, num+1):
        if num%x == 0:
            total += 1
    return total

print(triNum(2985))
##print(divs(triNum(3980)))
##cap = 500
##x = 1
##while divs(triNum(x)) != 500: 
##    x += 1
##print(triNum(x))
